workflows:
  maui-android-ios:
    name: .NET MAUI Android & iOS
    max_build_duration: 90
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      vars:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
        DOTNET_CLI_TELEMETRY_OPTOUT: "true"

    scripts:
      - name: Install .NET 8 SDK
        script: |
          brew install dotnet-sdk@8
          export DOTNET_ROOT="$(brew --prefix)/opt/dotnet@8/libexec"
          export PATH="$DOTNET_ROOT:$PATH"
          dotnet --version

      - name: Install MAUI workload (user local)
        script: |
          dotnet workload install maui --skip-sign-check

      - name: Restore dependencies
        script: |
          dotnet restore

      # -------- ANDROID --------
      - name: Build Android
        script: |
          dotnet publish YourProjectName.csproj \
            -c Release \
            -f net8.0-android \
            /p:AndroidPackageFormat=aab

      # -------- iOS --------
      - name: Build iOS
        script: |
          dotnet publish YourProjectName.csproj \
            -c Release \
            -f net8.0-ios \
            /p:RuntimeIdentifier=ios-arm64

    artifacts:
      - "**/*.aab"
      - "**/*.apk"
      - "**/*.ipa"
