workflows:
  maui-android-ios:
    name: .NET MAUI Android & iOS
    max_build_duration: 90
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      groups:
        - keystore_credentials
        - app_store_credentials

    scripts:
      - name: Install .NET SDK
        script: |
          brew install dotnet-sdk
          dotnet --version

      - name: Install MAUI workloads
        script: |
          dotnet workload install maui android ios

      - name: Restore dependencies
        script: |
          dotnet restore

      # ---------- ANDROID ----------
      - name: Build Android
        script: |
          dotnet publish AppMcvill.csproj \
            -c Release \
            -f net9.0-android \
            /p:AndroidPackageFormat=aab

      # ---------- iOS ----------
      - name: Build iOS
        script: |
          dotnet publish AppMcvill.csproj \
            -c Release \
            -f net9.0-ios \
            /p:RuntimeIdentifier=ios-arm64

    artifacts:
      - "**/*.aab"
      - "**/*.apk"
      - "**/*.ipa"
